# Interesting links: https://www.netlify.com/docs/continuous-deployment/

# Global settings applied to the whole site.
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
[build]
	command = "yarn build"
	functions = "./functions"
	publish = "public"
[build.environment]
	FOO = "bar"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
	[context.production.environment]
		ACCESS_TOKEN = "super secret"

[template.environment]
	FAUNADB_SECRET = "Your FaunaDB Server Secret"
